// Embedded card data — lets the app work even when opened directly as a
// local file (file://), where fetch() to separate JSON files is blocked
// by the browser. Keep this file next to index.html.
// Auto-generated by cards_data.js ジェネレーター on 2026-09-10
window.AIKATSU_SERIES_CONFIG = [
  {
    "id": "series_encore_1",
    "name": "2026年 第1弾",
    "badge": "",
    "cards": [
      {
        "id": "E1-21_N",
        "name": "E1-21_N",
        "image": "https://dcd.aikatsu.com/encore/images/cardlist/card/E1-21_N.webp",
        "rarity": "n"
      },
      {
        "id": "E1-22_N",
        "name": "E1-22_N",
        "image": "https://dcd.aikatsu.com/encore/images/cardlist/card/E1-22_N.webp",
        "rarity": "n"
      },
      {
        "id": "E1-23_N",
        "name": "E1-23_N",
        "image": "https://dcd.aikatsu.com/encore/images/cardlist/card/E1-23_N.webp",
        "rarity": "n"
      },
      {
        "id": "E1-24_N",
        "name": "E1-24_N",
        "image": "https://dcd.aikatsu.com/encore/images/cardlist/card/E1-24_N.webp",
        "rarity": "n"
      },
      {
        "id": "E1-25_N",
        "name": "E1-25_N",
        "image": "https://dcd.aikatsu.com/encore/images/cardlist/card/E1-25_N.webp",
        "rarity": "n"
      },
      {
        "id": "E1-26_N",
        "name": "E1-26_N",
        "image": "https://dcd.aikatsu.com/encore/images/cardlist/card/E1-26_N.webp",
        "rarity": "n"
      },
      {
        "id": "E1-27_N",
        "name": "E1-27_N",
        "image": "https://dcd.aikatsu.com/encore/images/cardlist/card/E1-27_N.webp",
        "rarity": "n"
      },
      {
        "id": "E1-28_N",
        "name": "E1-28_N",
        "image": "https://dcd.aikatsu.com/encore/images/cardlist/card/E1-28_N.webp",
        "rarity": "n"
      },
      {
        "id": "E1-29_N",
        "name": "E1-29_N",
        "image": "https://dcd.aikatsu.com/encore/images/cardlist/card/E1-29_N.webp",
        "rarity": "n"
      },
      {
        "id": "E1-41_N",
        "name": "E1-41_N",
        "image": "https://dcd.aikatsu.com/encore/images/cardlist/card/E1-41_N.webp",
        "rarity": "n"
      },
      {
        "id": "E1-42_N",
        "name": "E1-42_N",
        "image": "https://dcd.aikatsu.com/encore/images/cardlist/card/E1-42_N.webp",
        "rarity": "n"
      },
      {
        "id": "E1-43_N",
        "name": "E1-43_N",
        "image": "https://dcd.aikatsu.com/encore/images/cardlist/card/E1-43_N.webp",
        "rarity": "n"
      },
      {
        "id": "E1-44_N",
        "name": "E1-44_N",
        "image": "https://dcd.aikatsu.com/encore/images/cardlist/card/E1-44_N.webp",
        "rarity": "n"
      },
      {
        "id": "E1-45_N",
        "name": "E1-45_N",
        "image": "https://dcd.aikatsu.com/encore/images/cardlist/card/E1-45_N.webp",
        "rarity": "n"
      },
      {
        "id": "E1-46_N",
        "name": "E1-46_N",
        "image": "https://dcd.aikatsu.com/encore/images/cardlist/card/E1-46_N.webp",
        "rarity": "n"
      },
      {
        "id": "E1-47_N",
        "name": "E1-47_N",
        "image": "https://dcd.aikatsu.com/encore/images/cardlist/card/E1-47_N.webp",
        "rarity": "n"
      },
      {
        "id": "E1-48_N",
        "name": "E1-48_N",
        "image": "https://dcd.aikatsu.com/encore/images/cardlist/card/E1-48_N.webp",
        "rarity": "n"
      },
      {
        "id": "E1-49_N",
        "name": "E1-49_N",
        "image": "https://dcd.aikatsu.com/encore/images/cardlist/card/E1-49_N.webp",
        "rarity": "n"
      },
      {
        "id": "E1-51_PR",
        "name": "E1-51_PR",
        "image": "https://dcd.aikatsu.com/encore/images/cardlist/card/E1-51_PR.webp",
        "rarity": "pr"
      },
      {
        "id": "E1-52_PR",
        "name": "E1-52_PR",
        "image": "https://dcd.aikatsu.com/encore/images/cardlist/card/E1-52_PR.webp",
        "rarity": "pr"
      },
      {
        "id": "E1-60_N",
        "name": "E1-60_N",
        "image": "https://dcd.aikatsu.com/encore/images/cardlist/card/E1-60_N.webp",
        "rarity": "n"
      },
      {
        "id": "E1-61_N",
        "name": "E1-61_N",
        "image": "https://dcd.aikatsu.com/encore/images/cardlist/card/E1-61_N.webp",
        "rarity": "n"
      },
      {
        "id": "E1-62_N",
        "name": "E1-62_N",
        "image": "https://dcd.aikatsu.com/encore/images/cardlist/card/E1-62_N.webp",
        "rarity": "n"
      },
      {
        "id": "E1-63_N",
        "name": "E1-63_N",
        "image": "https://dcd.aikatsu.com/encore/images/cardlist/card/E1-63_N.webp",
        "rarity": "n"
      },
      {
        "id": "E1-64_N",
        "name": "E1-64_N",
        "image": "https://dcd.aikatsu.com/encore/images/cardlist/card/E1-64_N.webp",
        "rarity": "n"
      },
      {
        "id": "E1-65_N",
        "name": "E1-65_N",
        "image": "https://dcd.aikatsu.com/encore/images/cardlist/card/E1-65_N.webp",
        "rarity": "n"
      },
      {
        "id": "E1-66_N",
        "name": "E1-66_N",
        "image": "https://dcd.aikatsu.com/encore/images/cardlist/card/E1-66_N.webp",
        "rarity": "n"
      },
      {
        "id": "E1-67_N",
        "name": "E1-67_N",
        "image": "https://dcd.aikatsu.com/encore/images/cardlist/card/E1-67_N.webp",
        "rarity": "n"
      },
      {
        "id": "E1-68_N",
        "name": "E1-68_N",
        "image": "https://dcd.aikatsu.com/encore/images/cardlist/card/E1-68_N.webp",
        "rarity": "n"
      },
      {
        "id": "E1-69_N",
        "name": "E1-69_N",
        "image": "https://dcd.aikatsu.com/encore/images/cardlist/card/E1-69_N.webp",
        "rarity": "n"
      },
      {
        "id": "E1-70_N",
        "name": "E1-70_N",
        "image": "https://dcd.aikatsu.com/encore/images/cardlist/card/E1-70_N.webp",
        "rarity": "n"
      },
      {
        "id": "E1-83_N",
        "name": "E1-83_N",
        "image": "https://dcd.aikatsu.com/encore/images/cardlist/card/E1-83_N.webp",
        "rarity": "n"
      },
      {
        "id": "E1-84_N",
        "name": "E1-84_N",
        "image": "https://dcd.aikatsu.com/encore/images/cardlist/card/E1-84_N.webp",
        "rarity": "n"
      },
      {
        "id": "E1-85_N",
        "name": "E1-85_N",
        "image": "https://dcd.aikatsu.com/encore/images/cardlist/card/E1-85_N.webp",
        "rarity": "n"
      }
    ]
  }
];
